# Generated by Django 2.0 on 2019-03-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0002_auto_20190305_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmaster',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='channelstats',
            name='subscriber_count',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='videostats',
            name='comment_count',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='videostats',
            name='dislike_count',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='videostats',
            name='like_count',
            field=models.BigIntegerField(default=None),
        ),
    ]
